version: '3.8'

services:  
  blog_service:
    container_name: blog_service
    build: blog-starter-app
    # command: sh ./docker-entrypoint.sh
    restart: always
    image: blog-starter-app
    ports:
      - "3000:3000"
    networks:
      - public-network



networks:
  public-network:
    driver: bridge